# Generated by Django 5.0 on 2023-12-14 09:05

import django.db.models.deletion
import profile_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_lesson', models.IntegerField(default=0)),
                ('completed_test', models.IntegerField(default=0)),
                ('number_of_mistake', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('coins', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('rank', models.ForeignKey(blank=True, default=profile_app.models.get_first_rank, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='profile_app.rank')),
            ],
        ),
    ]
