# Generated by Django 5.0 on 2023-12-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/default_pics/user-icon-in-trendy-flat-style-isolated-on-grey-background-user-symbol-700-137463483.jpg', upload_to='profile_pics'),
        ),
    ]
